name: Daily Commit

on:
  schedule:
    - cron: "0 */2 * * *"   # Runs every 2 hours
  workflow_dispatch:         # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make dummy analytic-style commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Random number of commits (2–6) each run
          NUM=$(( ( RANDOM % 5 )  + 2 ))

          for i in $(seq 1 $NUM)
          do
            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
            value=$(( RANDOM % 500 + 50 ))   # random "metric" value
            echo "[$timestamp] visitors=$value" >> analytics.log
            git add analytics.log
            git commit -m "analytics: updated visitors=$value at $timestamp"
          done

          git push
